### ISSUE TITLE
LokiFsStructuredAdapter infinitely loops

### ISSUE THREAD

**Issue by derrxb** [recative/studio#1]
Hi! I found this project's TS implementation on this FsAdapter while trying to work on a bug in LokiJS's version. I adopted your version but encountered the following bug: 

There are instances where https://github.com/recative/studio/blob/05df74639ae4945ca2e27530474776dd846a6913/packages/loki-fs-structured-adapter/main.ts#L200 results in an infinite loop when loading a collection. As a result the `callback` for the `loadDatabase` function never triggers. This is because the collectionIndex never increments on the next call.

The linked code above should pass on the `internalCollectionIndex` as that is what is incremented on every pass. 

```TS
this.loadNextCollection(databaseName, internalCollectionIndex, callback);
```

**Comment by Losses** [comment]
Thank you for the fix! The pull request was merged!

**Comment by Losses** [comment]
@derrxb BTW, I'd recommend you try this one:
https://github.com/recative/studio/blob/main/src/main/utils/LokiFsStreamedAdapter.ts

It's a more robust implemented adapter, the behavior is similar to the default fs adapter, but used a lot of stream API, which means the data IO is not blocking.

I've read through every single line of the code of Loki.js, and found that the structuredAdapter is flawed from the ground, simply patch the adapter itself will mitigate the issue but won't solve the problem, including you may lose your data, or, even more, your file may be destroyed. We have used it in the production environment and experienced a lot of data related disaster.

To cope with these issues, I wrote a new adapter, it works fine on latest version of Node.js, and pretty stable (but not very fast, unfortunately), you can also have a try.

**Comment by derrxb** [comment]
Hey @Losses, 

Thanks for the recommendations! I will take a look at your recommended implementation. Speed-wise, do you have any info on the difference you can experience with using the streamed implementation?

We also had issues with LokiJS and had to look for fixes for the collections issue. I'm glad I came across your comment!

**Comment by Losses** [comment]
@derrxb I haven't tried any benchmark, but by observing how it works in the real world, the performance is indeed slower, but still acceptable.

I'd recommend you try it in your own project, ultimately, different projects have different requirement for data scales.
